require("spec.support.awesome_mocks")
local acpilight = require("continuity.backlight.backends.acpilight")

describe("backlight.acpilight backend", function()
	describe("_default_filter", function()
		it("passes names containing 'video'", function()
			assert.is_true(acpilight._default_filter("acpi_video0"))
		end)

		it("passes names containing 'backlight'", function()
			assert.is_true(acpilight._default_filter("intel_backlight"))
			assert.is_true(acpilight._default_filter("system76_acpi::kbd_backlight"))
		end)

		it("is case-insensitive", function()
			assert.is_true(acpilight._default_filter("ACPI_VIDEO0"))
			assert.is_true(acpilight._default_filter("Intel_Backlight"))
		end)

		it("rejects LED names", function()
			assert.is_false(acpilight._default_filter("phy0-led"))
			assert.is_false(acpilight._default_filter("input4::capslock"))
			assert.is_false(acpilight._default_filter("input4::numlock"))
			assert.is_false(acpilight._default_filter("input4::scrolllock"))
			assert.is_false(acpilight._default_filter("mmc0::"))
			assert.is_false(acpilight._default_filter("system76_acpi::airplane"))
		end)
	end)

	describe("_kind_from_name", function()
		it("returns 'keyboard' for names containing kbd", function()
			assert.equals("keyboard", acpilight._kind_from_name("system76_acpi::kbd_backlight"))
		end)

		it("returns 'keyboard' for names containing keyboard", function()
			assert.equals("keyboard", acpilight._kind_from_name("asus_keyboard"))
		end)

		it("returns 'display' for video devices", function()
			assert.equals("display", acpilight._kind_from_name("acpi_video0"))
		end)

		it("is case-insensitive", function()
			assert.equals("keyboard", acpilight._kind_from_name("KBD_backlight"))
		end)
	end)

	describe("_parse_line", function()
		it("parses name:brightness for simple names", function()
			local name, brightness = acpilight._parse_line("acpi_video0:21")
			assert.equals("acpi_video0", name)
			assert.equals(21, brightness)
		end)

		it("parses names containing colons (double-colon separator)", function()
			local name, brightness = acpilight._parse_line("system76_acpi::kbd_backlight:66")
			assert.equals("system76_acpi::kbd_backlight", name)
			assert.equals(66, brightness)
		end)

		it("handles float brightness values", function()
			local name, brightness = acpilight._parse_line("acpi_video0:21.000000")
			assert.equals("acpi_video0", name)
			assert.equals(21, brightness)
		end)

		it("returns nil for invalid format", function()
			local name, brightness = acpilight._parse_line("invalid")
			assert.is_nil(name)
			assert.is_nil(brightness)
		end)
	end)
end)
